spring:
    datasource:
        driverClassName: com.mysql.cj.jdbc.Driver
        password: ''
        url: jdbc:mysql://localhost:3306/indatacore_db?useSSL=false&allowMultiQueries=true&serverTimezone=UTC
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true
    servlet:
      multipart:
          max-file-size: 10MB
          max-request-size: 10MB
tokenSecret: jh5gt6dc5g41b9ju3s47
